### ISSUE TITLE
Correct left and right alignments in the Author page

### ISSUE THREAD

**Issue by ekiliar** [belaudiobooks/website#61]
Correct left and right alignments on the Author page
<img width="1378" alt="Screen Shot 2022-04-12 at 2 16 38 PM" src="https://user-images.githubusercontent.com/27494249/163028462-3ed3d23f-f279-40ca-9e7f-e0e57e3c6335.png">

**Comment by nbeloglazov** [comment]
@alexeylindin

**Comment by dein0s** [comment]
It actually only works as intended at medium (>=768px) and large (>=992px) breakpoints, everything else is scuffed.

width: 575
![image](https://github.com/belaudiobooks/website/assets/7908313/fd52fb87-f504-44c4-b10c-79be4446b96a)
width: 576
![image](https://github.com/belaudiobooks/website/assets/7908313/546dc799-f93f-43dd-8f32-a2480ea1ea1c)
width: 768
![image](https://github.com/belaudiobooks/website/assets/7908313/b72896f2-c1a4-4e05-b99b-f14e39ac0924)
width: 992
![image](https://github.com/belaudiobooks/website/assets/7908313/848c9ba6-cd00-4c5c-8cff-523a711bfb15)
width: 1200
![image](https://github.com/belaudiobooks/website/assets/7908313/c46b940e-0852-4b41-b2de-91973c9ff4c3)
width: 1400
![image](https://github.com/belaudiobooks/website/assets/7908313/107604a4-5c0c-4c5e-8798-6f1caf296237)

**Comment by nbeloglazov** [comment]
Fixed it in [349382a](https://github.com/belaudiobooks/website/commit/349382a7234f21e761789146157df5d2fbdacb68). Ended up migrating to CSS Grid to render book list.
