### ISSUE TITLE
Add links to reviews from livelib

### ISSUE THREAD

**Issue by nbeloglazov** [belaudiobooks/website#63]
Many (most) more or less popular belarusian books have reviews on livelib.ru. We should add link on each audiobook page to the corresponding page on livelib so that users can quickly see reviews. Would be cool to even embed reviews, but livelib doesn't provide API yet, [thread](https://www.livelib.ru/support/post/1354-api).

Example reviews for "Апошняя кніга пана А": https://www.livelib.ru/book/1004585776/reviews-aposhnyaya-kniga-pana-a-algerd-baharevich

**Comment by frombrest** [comment]
Does it make sense to generalize this task to add links to any review sources (not only livelib.ru)?
i.e. create new model ReviewLink and relation One (book) - to - Many (ReviewLink) and probably ReviewLinkType (or possibly reuse current LinkType model)

As I understand we are going to attach links manually at least initially? Because it would be difficult fully automate that.

**Comment by nbeloglazov** [comment]
Currently I'm hesitating between two options: provide link to some other website containing reviews or provide ability for visitors to leave review on our site. At this point I doubt we can pull off our own review system: I don't see signs that visitors would like to leave reviews + leaving reviews on a site that's blocked in Belarus might feel risky to many. 

As for your proposal multiple review sources for each book, let me first check if there are other potential sources. I'm sure there are other review platforms out there but maybe only livelib.ru has reviews for Belarusians books. And if that's the case I would keep it simple and didn't create one-to-many relationship.

**Comment by frombrest** [comment]
Any decisions on that? ⬆️

**Comment by nbeloglazov** [comment]
No, unfortunately not yet.

**Comment by nbeloglazov** [comment]
Got response. Yes, livelib is the main review platform and we should focus on it. I think we should start with a single review-platform link per book.

**Comment by frombrest** [comment]
So, task is: 
1. Add
```
livelib_url = models.CharField(_('LiveLib URL'), max_length=256, blank=True,  default='')
```
field to the book model.
2. Add url to book_detail template.
3. Add tests to make sure book_detail page shows url.

Question: Should we add some livelib icon to the static content to show near url?

**Comment by nbeloglazov** [comment]
Yes, and a few more (optional) tasks.
4. See if we can write a script to backfill existing books with livelib links. 
5. Update admin page for book creation to provide extra info on how to fill livelib field. If possible - add a link to the livelib search page. 

> Question: Should we add some livelib icon to the static content to show near url?
No. Let's start with a simple "Водгукі на LiveLib" link.

**Comment by nbeloglazov** [comment]
Added livelib links that @frombrest gathered from the script. So we can officially consider it launched in prod!

**Comment by nbeloglazov** [comment]
@frombrest if you implement endpoint that returns list of livelib urls - I can add it to the admin page.

**Comment by nbeloglazov** [comment]
Ok. I think we are done with this feature!
