### ISSUE TITLE
Add lacinky

### ISSUE THREAD

**Issue by nbeloglazov** [belaudiobooks/website#68]
Support belarusian lacinku. Given that government is actively trying to get rid of it, would be nice to expand its availability. We should talk with Nasha Niva who created auto-lacinizator. We can probably use thei if they ok to share. 
https://nashaniva.com/310889

Adding support requires refactoring code to support internationalization. Which can be useful in future if we decide to support Russian or English languages.

**Comment by dein0s** [comment]
Take a look at this resource as well: https://baltoslav.eu/lat/index.php?mova=by

Sadly, they do not provide any open API it seems.

**Comment by frombrest** [comment]
I'd rather propose to look at this resource: [https://slounik.org/lat](https://slounik.org/lat)
And their converter: [https://slounik.org/assets/js/lat/converter.js](https://slounik.org/assets/js/lat/converter.js)

But anyway we can not just to start using their software. We at least need to get their approval.

But better, what I would like to propose: Create as separated open source project (under belaudiobooks umbrella) set of libraries for different programming languages but with same set of test case to get consistent behavior and publish libraries to open repositories (pypi, npm, maven, etc...). Main purpose is not to provide end users transliteration functionality like many different online resources doing that, but provide developers quick, trusted and free way to instrument their software by this functionality.
Would be awesome if professional linguists help to write test cases.

**Comment by nbeloglazov** [comment]
Having open-source lacinizator is definitely something we could use. But I think it makes more sense for Nasha Niva to open-source theirs (if they want to), given that they are using it in production for a while now and I assume it's tested well. Re-implementing this library in different languages would be cool. But I expect there very few users for that functionality right now. Hm, I can see an approach where different implementations share common set of tests and algorithm description, as @frombrest suggested. At the same time each implementation is maintained by a different team/project who uses that library in their own codebase. For example for python it can be audiobooks.by. 

That might even warrant a separate github org if each implementation is a separate repo.

**Comment by frombrest** [comment]
> But I think it makes more sense for Nasha Niva to open-source theirs (if they want to), given that they are using it in production for a while now and I assume it's tested well.

Agree. If they ready to share their sources under open license like MIT it would be great since they have integration and usage expirience.
Btw, their implementation you can see here: 
```
view-source:https://nashaniva.com/?c=latn
line: 179
```
could you as an official representative of audiobooks.by send them requiest/proposal to publish their code as reference implementation under open license with tests if they have them? We of course can assist with technical questions.

> Re-implementing this library in different languages would be cool. But I expect there very few users for that functionality right now.

Yeah, that is definetly long term prospective, no need to do that right now. It is more like justification of statment: `create as separated open source project...`

**Comment by nbeloglazov** [comment]
Talked to Nasha Niva. They are ok with us using their lacinizator from https://nashaniva.com/?c=latn I asked about tests or having repo - they don't have checked-in tests. And I didn't see interest in open-sourcing / putting it in repo. So that's something we might need to do ourselves if we want to go that route.

**Comment by nbeloglazov** [comment]
We started working on python lacinization library: https://github.com/belaudiobooks/lacinka
