### ISSUE TITLE
Implement link ordering

### ISSUE THREAD

**Issue by nbeloglazov** [belaudiobooks/website#87]
Currently links are displayed in a random order. Or maybe it's not random and it's in the order they were added, but I feel like I've seen random as well. Anyway, we should provide a specific order. The reason is that some links are not available everywhere (e.g. Apple books available only in USA). Such links should go to the bottom and more popular and available links (youtube, podcasts) to be listed at the top.

**Comment by frombrest** [comment]
Does it make sense to add `weight` (0-100 default 10) filed for `LinkType` model to be able strictly define order?

**Comment by nbeloglazov** [comment]
Yes, I also was thinking about having something like weight.
